README.md, package.json, src/enhancer.js
* fix(query/reducer): attaching/detaching listeners correctly using
name - #17
* fix(enhancer): make firestoreInstance available through getFirestore
=> v0.1.0-beta.2

package-lock.json, src/enhancer.js, tests/unit/enhancer.js
I actually had time to fix this, so here you go!
=> Set store.firestore to firestoreInstance. Fixes #19

.travis.yml, package-lock.json, package.json, src/createFirestoreInstance.js, src/reducers/dataReducer.js, src/utils/query.js
* fix(core): config from `react-redux-firebase` could be overwritten depending on order of enhancers
* fix(reducer): docs are marked `null` when loaded and empty
* feat(core): start support for sub collections (reducer, meta)
* feat(build): `husky` added to enable `prepush` hook (runs `npm run lint`)
=> v0.1.0-beta.4

.gitignore, src/reducers/dataReducer.js, src/utils/query.js
Support subcollections of any depth.
=> Support subcollections of any depth

src/actions/firestore.js, src/utils/query.js, yarn.lock
https://github.com/prescottprue/react-redux-firebase/issues/392
I ran into a situation where my listeners were detaching, but they didn't have to so I implemented the solution of @Venryx
I thought that redux-firestore should manage its listeners internally. It shouldn't be firestoreConnect's responsibility to do this. 
=> feat(listeners): improve tracking of listeners

src/utils/query.js, test/unit/utils/query.spec.js
handleSubcollections returned the parent.
Fixed by making sure the result is assigned to ref and added test to assert the correct behaviour.
=> Fix handling of nested subcollections

README.md
1 work typo fix lisnter to listeners
=> fix(README.md): lisnter typo corrected

README.md
Updated README.md section Types of Queries to list unsetListener(s) functions and be more clear about query options
=>  docs(Types of Queries): general clarification and added unsetListener(s)

package-lock.json, package.json, src/reducer.js, src/reducers/crossSliceReducer.js, test/unit/helpers.js, test/unit/reducers/reducer.spec.js
* fix(compositeReducer): fix for disappearing `composite` slice - #128 - @demoran23
* fix(deps): remove `@types/lodash` from dev dependencies
* fix(deps): update `babel-preset-env` to 1.7.0
* #128
=> v0.6.0-alpha.2

README.md
=> Clearified sub collection string equivalent example

.babelrc, .eslintrc, .gitignore, README.md, examples/basic/jsconfig.json, jsconfig.json, package-lock.json, package.json, src/actions/firestore.js, src/constants.js, src/reducers/dataReducer.js, src/utils/async.js, src/utils/query.js, src/utils/reducers.js, test/unit/actions/firestore.spec.js, test/unit/utils/query.spec.js, test/unit/utils/reducers.spec.js
* fix(reducers): correctly update state for docs with keys that contain a dot when using storeAs - @compojoom
* feat(query): consolidate oneListenerPerPath and allowMultipleListeners logic - @alexmattson
* feat(query): initial support for populate - #48, [RRF 362](https://github.com/prescottprue/react-redux-firebase/issues/362)
* #48
* #143
=> v0.6.0-alpha.3

src/utils/query.js
=> fixed arrayToStr.

index.d.ts
more info: https://github.com/prescottprue/redux-firestore/issues/209
https://github.com/prescottprue/redux-firestore/issues/209
=> fix(enhancer): use Dispatch from redux to prevent compatibility issues with react-redux-firebase

examples/complete/README.md
- Basic steps to help newcomers to CRA + Firebase get started
- Added the section "Understanding The Code" to help newcomers navigate the redux-firestore capabilities in the example
- Updated the TOC to reflect the document structure
=> chore(examples): add "understanding the code" section to complete example README

README.md
A typo. Nothing much is going on here.
=> fix(docs): fix typo in README alow -> allow - @lynklody

index.d.ts
Non-breaking change. Simply exports all of the `actionTypes` for consistency.
=> fix(types): de-dupe action types by reusing existing const

examples/basic/src/Todo.js, examples/basic/src/Todos.js
Just cloned and tried the Examples and notice the Basic example refuse to run.
- [ ?] All tests passing
- [ ?] Docs updated with any changes or examples if applicable
- [ ?] Added tests to ensure new feature(s) work properly
=> fix(examples): correctly pass id in basic example

README.md
=> chore: update readme badge to point to publish workflow

.github/workflows/publish.yml, .github/workflows/verify.yml, .husky/commit-msg, .prettierrc, .prettierrc.js, README.md, commitlint.config.js, package.json, yarn.lock
=> chore(ci): switch publish to semantic-release

index.d.ts, package.json
NOTE: This is a breaking change because types will not work correctly with versions of firebase before v8 
=> feat(types): support firebase greater than v8
