prescottprue/redux-firestore

package.json

Added `prepare` script to build lib when the package is installed. 
I noticed there's also a `preversion` script which only runs when bumping the package version. Was `preversion` suppose to be `prepare`? Shall I remove `preversion`? Let me know.
More info on `npm` scripts:
https://docs.npmjs.com/misc/scripts
*Note: I think `prepare` only works with npm v4+, if we want to support npm < 4 we should use `prepublish`.*
Related to #1, #3.

👷 Add prepare script

---

README.md
index.d.ts
package-lock.json
package.json
src/actions/firestore.js
src/createFirestoreInstance.js
src/enhancer.js
src/index.js
src/utils/query.js

* feat(query): `where` support in queries (single Array or Array of Arrays)
* feat(query): `onSnapshot` is now an alias of `setListener`  instead of being its own function
* fix(query): correctly dispatching `LISTENER_ERROR` action type on query listener errors
* feat(query): query name within reducers includes `where`
* feat(core): `getFirestore` added to get internal `store.firestore` instance - #13
* feat(typings): `getFirestore` added to typscript typings
* feat(docs): README updated with Query options

v0.1.0-beta

---

src/reducers/listenersReducer.js
src/utils/query.js

Prior to this change, the `listenersReducer` is reading the `payload.id` while the action is dispatched with `name` property instead.
On top of that, while detaching listeners, the listener is not deleted, resulting in a warning of `Listener already exists`.

Fix attaching and detaching listeners

---

package.json
src/actions/firestore.js
src/reducers/dataReducer.js
src/reducers/orderedReducer.js
src/utils/query.js

* fix(listeners): `unsetListener` works all the time (instead of just when array config is passed)
* feat(reducers): `dataReducer` now supports merging data (useful if another query has written data to that same redux path)
* feat(reducer): `orderedReducer` includes logic to work with subcollections - #7

v0.1.0-beta.5

---

README.md
package.json
src/actions/firestore.js
src/reducers/dataReducer.js

* fix(core): `set`, `add`, and `remove` are correctly using subcollections
* fix(reducer): fix issue where data was not updated if query exists for doc and one of it's subcollections at the same time

v0.1.0-beta.6

---

src/reducers/dataReducer.js

When there is no previousData, the data was being stored in a nested object with doc as key.

fix(reducer): flatten response when doc meta is present

---

src/utils/query.js

Turns out the `basePath.concat` calls weren't assigned to the same variable again to be returned later.

Fix getQueryName to return string with doc and subcollections info

---

src/utils/query.js

Turns out if you pass in subcollections it'll be formatted as `{collections}/{doc}{subcollections}`. This PR fixes that to `{collections}/{doc}/{subcollections}`.

Add missing slash between subcollections and collections/doc query name

---

src/utils/query.js

Due to the last changes in the way we build the query (using recursive function) if one has 2 parameters for example:
where: [
['company_id', '==', companyId],
['active', '==', true],
],
only the last array would be used for the query, because we call the recursive function not with the accumulator from .reduce, but with the original ref that was passed to the function

fix(query): multiple where and orderBy arguments

---

src/utils/query.js

Subcollections were not returning the reference and because of this we were always fetching the parent doc.

Subcollections were not working

---

src/utils/query.js
test/unit/utils/query.spec.js

Fix query string parsing.
The queryStrToObj function is currently creating the wrong queryObj causing operations in the wrong document, for instance,  an update to /col1/doc1/col2/doc2/col3/doc3 would generate a wrong update on doc1.
The queryStrToObj now returns a nested config object using the subcollections syntax.
```
{
"collection": "col1",
"doc": "doc1",
"subcollections": [
{
"collection": "col2",
"doc": "doc2",
"subcollections": [
{
"collection": "col3",
"doc": "doc3"
}
]
}
]
}
```

Fix queryStr parsing of deep nested collections

---

README.md

Explained in the readme that the config options can be passed to reduxFirestore enhancer as optional second argument.

docs(Config Options): rfConfig can be passed to reduxFirestore enhancer

---

src/reducer.js
src/reducers/crossSliceReducer.js
test/unit/helpers.js
test/unit/reducers/reducer.spec.js

Since the cross slice reducer adds a slice, it doesn't exist when the other slices finish running.  If a non-impactful action is passed to the cross slice reducer and it decides it doesn't need to regenerate the composites, it will simply return `state` ... without a `composite` slice on it!
To fix this, a mock reducer has been added to `combinedReducers` that will retain state in that composed slice.
- [Y ] All tests passing
- [ N/A] Docs updated with any changes or examples if applicable
- [ Y] Added tests to ensure new feature(s) work properly

Fix for disappearing `composite` slice

---

src/reducers/crossSliceReducer.js

This one was a little tricky.  The code would test fine, actually debugged fine for me in React Native Android, but when I stopped debugging it would blow up.
replacing the `for-of` loop with a `.forEach` fixed the issue.
- [ Y] All tests passing
- [ N/A] Docs updated with any changes or examples if applicable
- [ N/A] Added tests to ensure new feature(s) work properly

Composite storeas

---

src/reducers/orderedReducer.js
test/unit/reducers/orderedReducer.spec.js

* fix(orderedReducer): `CLEAR_DATA` action correctly clears `ordered` state for actions dispatched without meta - #114
* fix(tests): update orderedReducer tests to include case of `CLEAR_DATA` action dispatched without `meta` - #114
* #114

fix(orderedReducer): CLEAR_DATA action correctly clears ordered state for actions dispatched without meta

---

index.d.ts

This returns a typescript error
```typescript
reduxFirestore(firebase)
```
```typescript
[ts] Expected 2 arguments, but got 1.
(alias) reduxFirestore(firebaseInstance: object, otherConfig: object): any
import reduxFirestore
A redux store enhancer that adds store.firebase (passed to React component context through react-redux's <Provider>).
```
Returns an error if the `otherConfig` attribute isn't passed.
According to the [README](https://github.com/prescottprue/redux-firestore/blame/master/README.md#L47) the second argument is optional. 

fix(typings): make otherConfig optional for enhancer in typings

---

.travis.yml
README.md
examples/complete/src/routes/Home/components/Home/Home.js
package-lock.json
package.json
src/index.js
src/reducers/dataReducer.js
src/reducers/orderedReducer.js
src/selectors.js
src/utils/query.js
src/utils/reducers.js
test/unit/reducers/dataReducer.spec.js
test/unit/reducers/orderedReducer.spec.js
test/unit/utils/reducers.spec.js

*Each bugfix will be checked off when it has been verified*
* #103
* #116 
* #140

v1.0.0-alpha

---

.gitignore
package.json
src/reducers/dataReducer.js
src/utils/reducers.js

Setwith in our datareducer can work with both a string and an array. If we do provide an array it will treat every element as separate object property. It won't try to transform
com.something.else into
com : { something: {else: ...}}}
but it will treat it as com.something.else = value
This seems to solve our issues with wrong paths for documents that contain a dot.
https://github.com/prescottprue/redux-firestore/issues/139

fix for storeAs and documents that contain a dot

---

README.md
src/actions/firestore.js
src/constants.js
test/unit/actions/firestore.spec.js

The logic for `oneListenerPerPath: true` and `allowMultipleListeners: false` greatly overlapped. This PR removes the `oneListenerPerPath` config option and instead opts to standardize that functionality as the default. Now whenever you call the setListeners/unsetListeners it will track the number of listeners set up. Also gives the opt out with `allowMultipleListeners: true`
Changes:
1) Updated `setListeners` and `unsetListeners` functions 
2) Changed `oneListenerPerPath` tests to `allowMultipleListeners` tests
3) removed `oneListenerPerPath` from docs

Consolidate oneListenerPerPath and allowMultipleListeners logic 

---

src/reducers/crossSliceReducer.js

For some reason the code in this pull request
https://github.com/prescottprue/redux-firestore/pull/130
breaks react-native in non-debug mode.
With those changes here it is working fine
https://github.com/prescottprue/redux-firestore/pull/130/files/f7af74872ffcbb2da80395050b0afb08c0e57334
@prescottprue - as discussed here https://github.com/prescottprue/redux-firestore/pull/130 with your proposed changes non-debug mode in react native on android works fine. 
https://github.com/prescottprue/redux-firestore/pull/130

fix(reducers): non-debug mode for react-native on android

---

src/utils/query.js

Related to issue #169
Made sure we don't lose the document `id` when populating.
#169

Made sure getPopulateChild includes object id

---

README.md
index.d.ts
package-lock.json
package.json
src/actions/firestore.js
src/utils/query.js
test/unit/reducers/reducer.spec.js

- updates the TypeScript definitions for the Config
- in ` src/utils/query.js`, changes `getQueryName()` to return `storeAs` if defined, or appends all query params to enable pagination
- in `src/utils/query.js`, changes `getBaseQueryName()` to append all query params to enable pagination
- adds a relevant test in `test/unit/reducers/reducer.spec.js`
- removes a hack in `src/actions/firestore.js` because solved by the two changes above
#144 #107

fix(query): getQueryName correctly handles storeAs to allow for pagination

---

src/createFirestoreInstance.js

This fix adds the missing spread operator to `defaultConfig` in `createFirestoreInstance`
#184

fix(config): fix merging default configs in createFirestoreInstance()

---

index.d.ts

With `noImplicitAny` setting enabled, projects are not compiling when type hints are missing. This fixes it.
#194

fix(typings): set type hints for onAttemptCollectionDelete

---

package-lock.json
src/utils/query.js
test/unit/actions/firestore.spec.js

Our team ran into an issue. We were listening to a collection with 3 documents, then we remove the 3 documents in a batch, but redux-firestore only removes one. 
It turned out that it is because redux-firestore adds a doc property to the meta object. The meta object should actually be a copy of the original meta, but since we don't do a deep clone there we end up modifying the original object.

fix(query): fix document updates by using deep clone on doc change event

---

src/reducers/orderedReducer.js
src/utils/query.js
test/unit/reducers/orderedReducer.spec.js
test/unit/utils/query.spec.js

* Set data record to null when fetched doc doesn't exist
* don't update existing ordered state when doc doesn't exist
* Add relevant tests
#179

fix(query/reducer): prevent updates to ordered when non-existent doc is queried

---

README.md
package-lock.json
package.json
src/constants.js
src/utils/query.js
test/unit/utils/query.spec.js

Adds support for collectionGroup queries.
I don’t feel confident enough to write additional tests so hoping someone else can pick this up.
* #221

feat(query): support for collectionGroup query

---

.github/FUNDING.yml
src/reducers/statusReducer.js
test/unit/reducers/statusReducer.spec.js

This PR makes sure that the `requested` and `requesting` status of `state.firestore.status` is updated when a listener is unset.
This is needed to prevent document paths being stuck forever on `requesting: true`, in case that a listener is unset before the document was fully loaded.
#232

fix(statusReducer): UNSET_LISTENER action type correctly updates status

---

src/actions/firestore.js
src/index.js
src/utils/query.js
test/unit/utils/query.spec.js

Add snapshot cache
```
Get DocumentSnapshot and QuerySnapshot with object from either data or
ordered firestore state. If provided with doc data, it will return
DocumentSnapshot, providing with a collection from data or an array from
ordered state will return QuerySnapshot, except ordered state that generated
as DocumentRef will return DocumentSnapshot
Note: the cache is local and, not persistance. Passing an object from initial
state or from SSR state will yield undefined.
```
https://github.com/prescottprue/redux-firestore/issues/203

feat(core): add snapshot cache

---

src/utils/query.js
test/unit/utils/query.spec.js

I had incorrect data snapshot type for WeakMap value. Have it fixed to be DocumentSnapshot and added the missed test to it.  
https://github.com/prescottprue/redux-firestore/issues/257

fix(query): fix snapshot cache - @illuminist

---

src/utils/query.js

When using the `populates` facility in a query, the `storeAs` property is ignored, and the data that is retrieved is always saved at the root. This means that multiple queries that use the `populates` facility with the same root will fail (subsequent queries will clear out earlier ones).
This small change allows the use of `storeAs` to place the retrieved data in a distinct location.

feat(query): support `storeAs` property in `populates` objects in queries - @jfrumar-infinitusai 

---

examples/complete/README.md
examples/complete/src/routes/Projects/routes/Project/components/PopulatedDetails/PopulatedDetails.enhancer.js
examples/complete/src/routes/Projects/routes/Project/components/PopulatedDetails/PopulatedDetails.js
examples/complete/src/routes/Projects/routes/Project/components/PopulatedDetails/PopulatedDetails.styles.js
examples/complete/src/routes/Projects/routes/Project/components/PopulatedDetails/index.js
examples/complete/src/routes/Projects/routes/Project/components/ProjectDetails/ProjectDetails.enhancer.js
examples/complete/src/routes/Projects/routes/Project/components/ProjectDetails/ProjectDetails.js
examples/complete/src/routes/Projects/routes/Project/components/ProjectDetails/ProjectDetails.styles.js
examples/complete/src/routes/Projects/routes/Project/components/ProjectDetails/index.js
examples/complete/src/routes/Projects/routes/Project/components/ProjectPage/ProjectPage.js

Update the "complete" example to show both standard useFirestoreConnect() and withPopulatedProjects -- that is, compose(firestoreConnect() + populate())

chore(docs): add populate example to project page

---

README.md

The word "closley" is incorrect. Changing to "closely"

fix(docs): fixing spelling error in storeAs description

---

src/reducers/orderedReducer.js
test/unit/reducers/orderedReducer.spec.js

When a DOCUMENT_MODIFIED && newIndex !== oldIndex the `id` of the ordered document is removed. This fix ensures that the meta.doc is spread into the newly changed document. 
https://github.com/prescottprue/redux-firestore/issues/292

fix: preserve id on DOCUMENT_MODIFIED reordering

---

README.md

- made example for `startAfter` more involved since it otherwise is just a duplicate of `startAt`
- consistency in formatting of **Note:** sections

fix(docs): enhanced example in README

---

src/createFirestoreInstance.js
src/index.js

This PR fixes the issues with getFirestore() function not returning the firestore object as mentioned in https://github.com/prescottprue/react-redux-firebase/issues/839#issuecomment-579795781 . To fix it, I've modelled the getFirestore functionality after the getFirebase() function in react-redux-firebase and moved the getFirestore function to createFirestoreInstance. 
https://github.com/prescottprue/react-redux-firebase/issues/785
https://github.com/prescottprue/react-redux-firebase/issues/839

fix(getFirestore): correctly load extended firestore instance in getFirestore

---

src/reducers/orderedReducer.js

I came across a bug in the orderedReducer
```
// Support moving a doc within an array
if (action.payload.ordered) {
const { newIndex, oldIndex } = action.payload.ordered;
// newIndex value exists, item was within array before, and the index has changed
if (!!newIndex && oldIndex > -1 && newIndex !== oldIndex) {
return newArrayWithItemMoved(
collectionState,
action.meta,
action.payload.ordered,
action.payload.data,
);
}
}
```
In this expression ` (!!newIndex && oldIndex > -1 && newIndex !== oldIndex)`, if newIndex is equal to zero it will skip reordering the data and just update the document in place. 
In this PR I've updated that expression to something that I think is more robust.

fix(orderedReducer): reorder items when newIndex is zero

---

index.d.ts

When Firebase releases v8 they did 3 breaking changes: https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020
No usage of `experimentalTabSynchronization` or `timestampsInSnapshots ` was found in this codebase.
The old import `import * as firebase from 'firebase/app'` has been replaced by the new import `import firebase from 'firebase/app'`
https://github.com/prescottprue/redux-firestore/issues/312

feat(types): required import convention for firebase 8
